### ISSUE TITLE
Wunderbar Strata

### ISSUE THREAD

**Issue by Sooleawa** [Toxicom/toxiui#144]
### Description
Unable to click the lower side of buttons in pet battles.

### ToxiUI Status Report
![image](https://github.com/user-attachments/assets/7637ba7d-e664-4225-9aba-cdb74fe04285)

### Screenshots
Normal wunderbar
![image](https://github.com/user-attachments/assets/5c361ff5-99b6-4002-986d-e1c89e4b22ee)
In petbattle, cant click lower side of buttons, red area
<img width="292" alt="image" src="https://github.com/user-attachments/assets/e8d50eee-e1de-490c-b1d8-5605ba70b908">
fstack on upper side of petbattle buttons
![image](https://github.com/user-attachments/assets/a380b1a6-5ec6-4d89-be70-73a00bbe9224)
fstack on lower side of petbattle buttond
![image](https://github.com/user-attachments/assets/b0e27983-3c0c-4c78-87fb-b895221c539d)
![image](https://github.com/user-attachments/assets/31f0b9d5-2023-4949-b40d-36cddb64065e)

### To reproduce
1. Do pet battle
2. click lower side of buttons
3.

minor inconvenience :)

**Comment by Toxicom** [comment]
The problem is that even if I set WunderBar's strata to `"BACKGROUND"`, ElvUI's pet battle action bars are also at the same strata level, so this achieves nothing.
![image](https://github.com/user-attachments/assets/136c5e35-e50e-45c5-b51f-ffbbf987c3f7)

Another solution would be to kill the wunderbar on fade out, but that would definitely be a huge performance loss, as we would have to re-create wunderbar each time people fade in.

Not going to fix this, too little gain for much refactoring.
