### ISSUE TITLE
WunderBar: ElvUI tooltips

### ISSUE THREAD

**Issue by Toxicom** [Toxicom/toxiui#39]
### Description

ElvUI is refactoring their data texts and since in WunderBar we mostly re-use their datatexts, our tooltips are now broken. I've recently disabled the guild tooltip in the micromenu, but soon more of them should break.

I see two options moving forward:
1. Re-hook to the new ElvUI data texts
2. Create our own tooltips

Option one is obviously easier, but we'd again be dependant on ElvUI and any changes from them would break us again.

### Notes

- Some datatext commits on elvui https://github.com/tukui-org/ElvUI/commits/development?after=077369c8e695bfd2d115f2fbe31f9d1d780459ed+139&branch=development&qualified_name=refs%2Fheads%2Fdevelopment

### To reproduce

1. Hover guild icon in wunderbar micromenu
2. Tooltip will not show

### Acceptance criteria

- [ ] WunderBar tooltips are working
- [ ] Optional: ElvUI modules in wunderbar are working

**Comment by Toxicom** [comment]
Update: more tooltips are now broken with recent ElvUI updates (13.23?)

**Comment by NoelHendrikx** [comment]
I have disabled the Wunderbar Datatext module, since it gives me lua errors for:
- System, time and Friends icons 

ElvUI 13.27

Time:
Message: ...terface/AddOns/ElvUI/Core/Modules/DataTexts/Time.lua:84: attempt to index upvalue 'db' (a nil value)
Time: Sat Mar 18 03:53:57 2023
Count: 1
Stack: ...terface/AddOns/ElvUI/Core/Modules/DataTexts/Time.lua:84: attempt to index upvalue 'db' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/Time.lua"]:84: in function <...terface/AddOns/ElvUI/Core/Modules/DataTexts/Time.lua:83>
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/Time.lua"]:295: in function `onEnter'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/WunderBar/SubModules/Time.lua"]:91: in function `OnEnter'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/WunderBar/Modules.lua"]:132: in function `ModuleOnEnter'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/WunderBar/Modules.lua"]:289: in function <...ce/AddOns/ElvUI_ToxiUI/Modules/WunderBar/Modules.lua:288>

Locals:

**Comment by Toxicom** [comment]
https://github.com/Toxicom/toxiui/pull/48
