### ISSUE TITLE
[Question] No listed way to change % to actual on class power bar

### ISSUE THREAD

**Issue by Redledr** [Toxicom/toxiui#93]
### Description
What is the issue about?
No listed way to change % to actual on class power bar
### Lua error
```lua
None.
```

### ToxiUI Status Report
Type `/tx status` in game and paste a screenshot of it here.
![image](https://github.com/Toxicom/toxiui/assets/37914092/c499525b-55b9-4f68-9ea3-c3aeadf27f0f)

**Comment by Toxicom** [comment]
I'm having trouble seeing how useful this actually is.
- For target & boss frames, the percentage is more relevant since spells get cast at certain thresholds
- For party, I doubt there are scenarios where you would know the exact value of the heal and know if they have one more cast in them; Just knowing that they're low in percentages makes more sense
- For player, the majority of people use WeakAuras, so introducing this option for the minority that use ElvUI power bar is a waste of code and additional computing, since it's very simple to change one text tag

If I'm missing something, please feel free to argue but as it stands right now I don't see this being implemented 🤔

**Comment by Redledr** [comment]
All very good points. No argument there. There's an "Old Style" and "New Style" for the unitframes, and I made a wrong assumption it would apply to the manabar as well. When it did not, I did not know whether it was on purpose or my install had an issue. Especially since the "Old Style" says it's for those who want more information and does not touch specifically on the healthbar. My apologies.

Thanks for your time, its a wonderful UI.

**Comment by Toxicom** [comment]
We do set the power tag differently based on version
```lua
text_format = F.ChooseForTheme(TXUI.IsVanilla and "[tx:smartpower]" or "[tx:smartpower:percent:nosign]", "[tx:power:percent:nosign]"),
```
Do you think the full power format should apply for Cata too? I'm happy to make that change :)

**Comment by Redledr** [comment]
I think although a niche view of mana, it's a beneficial change to some of us who have always used the "Numeric Value" option for the default blizzard frames. I hate having to waste your time or make a sales pitch, but there's a lot of comfort in that view, but again, I apologize for the change suggestion for the minority!
